# Generated by Django 5.0.7 on 2024-08-24 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistas', '0004_alter_artista_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('enviada', models.BooleanField(default=False)),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artistas.artista')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
            },
        ),
    ]
