# Generated by Django 5.0.7 on 2024-08-24 03:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistas', '0005_mensagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='data_envio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
